# Generated by Django 4.0.4 on 2022-05-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
